# test file 1 for module Config::IniFile::Subst
key1 = wert1
    key2         =        "wert2
key3 =
key4 = bla#bla
key5 = blabla #
key6 = test
errfile = /foo/bar\my.err
testdir1 = /foo/bar
testdir2 = /foo/bar/
testdir3 = /foo/bar\
[sectiona]
key1 = key1a
key2 = key2x
[sectionb]
key1 = key1b
