# escape test file for module Config::IniFile::Subst
key0  = rhabarber
key1  = rha\tbarber
resolve_escapes: 1
keya  = rha\abarber
keyb  = rha\bbarber
keyf  = rha\fbarber
keyn  = rha\nbarber
keyr  = rha\rbarber
keyt  = rha\tbarber
keyv  = rha\vbarber
keydq = rha\"barber
keysq = rha\'barber
keyqm = rha\?barber
keybs = rha\\barber
keyx1 = rha\xaxarber
keyx2 = rha\xabxarber
keyx3 = rha\xabarber
keyo1 = rha\1arber
keyo2 = rha\11arber
keyo3 = rha\111arber
keyo4 = rha\1111arber
resolve_escapes: 0
keyz1 = rha\tbarber
resolve_escapes:
keyz2 = rha\tbarber
include: t/test4.ini
