# test file 2 for module Config::IniFile::Subst
key6 = "blubber "
key7 = rhabarber plus
key8 = %key3%rhabarber
key9 = rha%key2%bar%key1%ber
key10 = rha%key2%bar%key3%ber
key11 = %key11%
key12 = rha%key11%bar%key6%ber
key13 = rose = rose = rose
include: t/test3.ini
