# test file 0 for IniFile
ERRFILE=/foo/bar\my.err
KEY1=wert1
KEY2="wert2
KEY3=
KEY4=bla#bla
KEY5=blabla #
KEY6=test000
KEY7=key7a
KEY8=key8a
KEY9=test\tspace
TESTDIR1=/foo/bar
TESTDIR2=/foo/bar/
TESTDIR3=/foo/bar\
[SECTIONA]
KEY1=key1a
[SECTIONB]
KEY1=key1b
[]
KEY6=test2
[SECTIONA]
KEY2=key2x
[ ]
KEY10=more test
KEY11=
KEY12
 = dummy
