# include test file 2 for IniFile (use with 00-config.ini)
key6 = "blubber "
key20 = rhabarber plus
key21 = %key3%rhabarber
key22 = rha%key2%bar%key1%ber
key23 = rha%key2%bar%key3%ber
key24 = %key24%
key25 = rha%key24%bar%key6%ber
key26 = rose = rose = rose
[sectionb]
include: t\00-include2a.ini
key27 = key27a
key28 = %[sectiona]key2%
key29 = %key2%
key30 = %[]key2%
key31 = %[ ]key2%
key32 = % key2%
key33 = %key2 %
key34 = %  key2  %
