# test file 1 for IniFile
key01 = test\tspace
resolve_escapes:
key02 = test\tspace
resolve_escapes: 0
key03 = test\tspace
resolve_escapes: 1
key04 = test\tspace
key10 = test\aspace
key11 = test\bspace
key12 = test\fspace
key13 = test\nspace
key14 = test\rspace
key15 = test\vspace
key16 = test\'space
key17 = test\"space
key18 = test\?space
key19 = test\\space
key20 = 'test\'space'
key21 = "test\"space"
key22 = test\7space
key23 = test\11space
key24 = test\011space
key25 = test\0114space
key26 = test\78space
key27 = test\x9space
key28 = test\x09space
key29 = test\x094space
key30 = test\xspace
key31 = test\space
key32 = testspace\x
key33 = testspace\x9
key34 = testspace\x09
key35 = testspace\
key36 = testspace\7
key37 = testspace\11
[sectiona]
key01 = test\tspace
[]
include: t\01-include1.ini
key05 = test\tspace
resolve_escapes: 0
include: t\01-include2.ini
key06 = test\tspace
